export const en = {
  introducing: "Introducing Your Next E-Commerce Solution!",
  highQuality: "High-Quality, Multilingual, and Ready in Just One Day!",
  eCommerce: "E-commerce",
  template: "template",
  visit: "Visit",
  launch: "Launch Your Store in Just One Day!",
  noNeed: "No technical expertise needed.",
  fullyOperational: "Fully operational in 24 hours.",
  designed: "Designed for everyone.",
  global: "Global Reach with Local Touch!",
  languageSupported: "Languages supported:",
  georgian: "Georgian",
  ka: "Ka",
  english: "English",
  en: "en",
  russian: "Russian",
  ru: "ru",
  expand: "Expand your market effortlessly.",
  allInOne: "All-in-One Admin Dashboard!",
  manage: "Manage orders, users, products, and shipping.",
  control: "Control store content, advertisements, and special offers.",
  detailed: "Detailed analytics for finances and orders.",
  addMember: "Add team members with customizable access.",
  dashboardOverview: "Dashboard Overview",
  built: "Built for Performance and Engagement!",
  tested: "100% tested for reliability and performance.",
  autoEmails: "Automatic email notifications for key actions.",
  inApp: "In-app chat for direct communication with users.",
  sendingEmails: "Sending emails to user or user's group from dashboard.",
  advancedTechnology: "Advanced Technology",
  builtMERN: "Built on the Cutting-Edge MERN Stack.",
  highQualityAndScalable: "High-quality, scalable, and secure.",
  paymentSystem: "Payment System",
  integratedPayments: "Integrated payment systems for seamless transactions.",
  anyPayment: "Any payment system by business choice!",
  whyOurEstore: "Why Our E-Store Stands Out?",
  quickSetup: "Quick setup with no compromise on quality",
  supports: "Supports three key languages to maximize your reach.",
  robust: "Robust admin dashboard puts you in control.", // Corrected "rebust" to "robust"
  proven: "Proven reliability with a focus on user engagement.",
  ready: "Ready to Launch Your E-Store?",
  transform: "Transform your e-commerce vision into reality.",
  phone: "Phone",
  email: "Email",
  name: "Name",
  provideEmail: "Please provide an email...",
  provideName: "Please provide a name...",
  providePhone: "Please provide a phone number...",
  success: "The Request has been sent successfully!", // Corrected "succesfully" to "successfully"
  form: "Request Form", // Added "Here" at the beginning for clarity
  optional: "(Optional)",
  send: "Send",
  wrong: "Something went wrong!",
  message: "Message...",
};

export const ka = {
  introducing: "წარმოგიდგენთ თქვენს მომავალ E-Commerce გადაწყვეტას!",
  highQuality: "მაღალი ხარისხის, მრავალენოვანი და მზად არის მხოლოდ ერთ დღეში!",
  eCommerce: "ელექტრონული კომერცია",
  template: "შაბლონი",
  visit: "ვიზიტი",
  launch: "გაუშვით თქვენი მაღაზია მხოლოდ ერთ დღეში!",
  noNeed: "არ არის საჭირო ტექნიკური ექსპერტიზა.",
  fullyOperational: "სრული ფუნქციონირება 24 საათში.",
  designed: "შემუშავებული ყველასთვის.",
  global: "გლობალური მიღწევა ლოკალური შეხებით!",
  languageSupported: "ენები მხარდაჭერილია:",
  georgian: "ქართული",
  ka: "ქართ.",
  english: "ინგლისური",
  en: "ინგლ.",
  russian: "რუსული",
  ru: "რუს.",
  expand: "გააფართოვე შენი ბაზარი ძალისხმევის გარეშე.",
  allInOne: "ყველაფერი ერთ ადმინ პანელში!",
  manage: "შეკვეთების, მომხმარებლების, პროდუქტების და მიწოდების მართვა.",
  control:
    "მაღაზიის კონტენტის, რეკლამებისა და სპეციალური შეთავაზებების კონტროლი.",
  detailed: "დეტალური ანალიტიკა ფინანსებისა და შეკვეთებისთვის.",
  addMember: "დაამატეთ გუნდის წევრები მორგებული წვდომით.",
  dashboardOverview: "პანელის მიმოხილვა",
  built: "აშენებული შესრულებისა და ჩართულობისთვის!",
  tested: "100% შემოწმებული საიმედოობისა და შესრულებისთვის.",
  autoEmails: "ავტომატური ელფოსტის შეტყობინებები ძირითადი მოქმედებებისთვის.",
  inApp: "აპლიკაციის შიგნით ჩატი მომხმარებლებთან პირდაპირი კომუნიკაციისთვის.",
  sendingEmails:
    "ელფოსტის გაგზავნა მომხმარებლის ან მომხმარებლის ჯგუფში დაფიდან.",
  advancedTechnology: "მოწინავე ტექნოლოგია",
  builtMERN: "აშენებული უახლესი MERN დასტაზე.",
  highQualityAndScalable: "მაღალი ხარისხის, მასშტაბირებადი და უსაფრთხო.",
  paymentSystem: "გადახდის სისტემა",
  integratedPayments:
    "ინტეგრირებული გადახდის სისტემები უწყვეტი ტრანზაქციებისთვის.",
  anyPayment: "ნებისმიერი გადახდის სისტემა ბიზნესის არჩევანით!",
  whyOurEstore: "რატომ გამოირჩევა ჩვენი ელექტრონული მაღაზია?",
  quickSetup: "სწრაფი დაყენება ხარისხზე კომპრომისის გარეშე",
  supports: "მხარდაჭერილია სამი ძირითადი ენა თქვენი წვდომის გაზრდის მიზნით.",
  rebust: "მძლავრი ადმინისტრატორის დაფა გაძლევს კონტროლს.",
  proven: "დადასტურებული საიმედოობა მომხმარებლის ჩართულობაზე ფოკუსირებით.",
  ready: "მზად ხარ შენი ელექტრონული მაღაზიის გასაშვებად?",
  transform: "გარდაქმენით თქვენი ელექტრონული კომერციის ხედვა რეალობად.",
  phone: "ტელეფონი",
  email: "ელ-ფოსტა",
  name: "სახელი",
  provideEmail: "გთხოვთ შეიყვანოთ ელფოსტა...",
  provideName: "გთხოვთ შეიყვანოთ სახელი...",
  providePhone: "გთხოვთ შეიყვანოთ მობილურის ნომერი...",
  success: "მოთხოვნა წარმატებით გაიგზავნა!!",
  form: "მოთხოვნის ფორმა",
  optional: "(სურვილისამებრ)",
  send: "გაგზავნა",
  wrong: "დაფიქსირდა შეცდომა!",
  message: "კომენტარი...",
};

export const ru = {
  introducing: "Представляем ваше следующее решение для электронной коммерции!",
  highQuality:
    "Высокое качество, многоязычность и готовность всего за один день!",
  eCommerce: "Электронная коммерция",
  template: "шаблон",
  visit: "Посетите",
  launch: "Запустите ваш магазин всего за один день!",
  noNeed: "Технические навыки не требуются.",
  fullyOperational: "Полностью оперативный за 24 часа.",
  designed: "Разработан для каждого.",
  global: "Глобальное присутствие с местным подходом!",
  languageSupported: "Поддерживаемые языки:",
  georgian: "Грузинский",
  ka: "ka",
  english: "Английский",
  en: "en",
  russian: "Русский",
  ru: "ru",
  expand: "Легко расширьте ваш рынок.",
  allInOne: "Все в одной административной панели!",
  manage: "Управляйте заказами, пользователями, продукцией и доставкой.",
  control:
    "Контролируйте содержимое магазина, рекламу и специальные предложения.",
  detailed: "Подробная аналитика финансов и заказов.",
  addMember: "Добавьте членов команды с настраиваемым доступом.",
  dashboardOverview: "Обзор панели управления",
  built: "Построен для производительности и вовлеченности!",
  tested: "100% проверено на надежность и производительность.",
  autoEmails:
    "Автоматические уведомления по электронной почте для ключевых действий.",
  inApp: "Чат в приложении для прямого общения с пользователями.",
  sendingEmails:
    "Отправка электронных писем пользователю или группе пользователей с панели управления.",
  advancedTechnology: "Передовые технологии",
  builtMERN: "Построен на передовом стеке MERN.",
  highQualityAndScalable: "Высококачественный, масштабируемый и безопасный.",
  paymentSystem: "Платежная система",
  integratedPayments:
    "Интегрированные платежные системы для бесперебойных транзакций.",
  anyPayment: "Любая платежная система по выбору бизнеса!",
  whyOurEstore: "Почему наш электронный магазин выделяется?",
  quickSetup: "Быстрая настройка без ущерба для качества",
  supports: "Поддерживает три ключевых языка для максимизации вашего охвата.",
  robust: "Надежная административная панель дает вам контроль.",
  proven: "Доказанная надежность с акцентом на вовлеченность пользователей.",
  ready: "Готовы запустить ваш электронный магазин?",
  transform: "Превратите ваше видение электронной коммерции в реальность.",
  phone: "Телефон",
  email: "Электронная почта",
  name: "Имя",
  provideEmail: "Пожалуйста, укажите электронную почту...",
  provideName: "Пожалуйста, укажите имя...",
  providePhone: "Пожалуйста, укажите номер телефона...",
  success: "Сообщение успешно отправлено!",
  form: "Форма запроса",
  optional: "(Необязательно)",
  send: "Отправить",
  wrong: "Что-то пошло не так!",
  message: "Сообщение...",
};
